---
 - name: install and configure apache2
   hosts: "{{ nodes }}"
   become: yes
   vars:
   vars_files:  
   tasks:
     - name: Include a variable file for this play
       include_vars: vars.yml
     - name: Install {{ web_package }} and {{ firewalld_package }}
       apt:
         name: 
           - "{{ web_package }}"
           - "{{ firewalld_package }}"
         state: latest
     - name: Enable {{ web_service }}
       service:
         name: "{{ web_service }}"
         enabled: true
         state: started

     - name: Enable {{ firewalld_service }}
       service:
         name: "{{ firewalld_service }}"
         enabled: true
         state: started

     - name: Open firewalld ports
       firewalld:
         service: http
         permanent: true
         state: enabled
         immediate: yes

     - name: Copy html content
       copy:
         content: "welcome to our website <br> (This is deplyed using Ansible)"
         dest: /var/www/html/index.html


 - name: Test and Verify Webservers
   hosts: localhost
   become: no
   tasks:
     - name: Connect to the webserver
       uri:
         url: http://54.159.223.116
         status_code: 200

